version: '3'

services:
  
  app:
    image: mcr.microsoft.com/devcontainers/python:dev-3.12-bookworm
    command: tail -f /dev/null
    volumes:
      - .:/workspace:cached

  db:
    image: mysql:8.3.0
    container_name: mymysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password